[env:esp32-s3-devkitc-1]

platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino


; ============================================================
; ESP32-S3-DevKitC-1 N32R16V
; 32MB Octal Flash + 16MB Octal PSRAM
; 这是你之前已经跑通的板卡配置，不要再改成 qio
; ============================================================

board_build.arduino.memory_type = opi_opi
board_build.flash_mode = opi
board_build.psram_type = opi

board_upload.flash_size = 32MB

; 当前使用已经验证可用的 8MB 分区表
; Flash 芯片本身仍然是 32MB
board_build.partitions = default_8MB.csv

board_build.extra_flags =
    -DBOARD_HAS_PSRAM


; ============================================================
; 串口
; ============================================================

monitor_speed = 115200
upload_speed = 460800

upload_port = COM8
monitor_port = COM8


; ============================================================
; 原 V1.2 全部依赖 + OLED
; ============================================================

lib_deps =

    ; MPU6050
    adafruit/Adafruit MPU6050

    ; BMP280 / BME280
    adafruit/Adafruit BMP280 Library
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit Unified Sensor

    ; GPS
    mikalhart/TinyGPSPlus @ 1.1.0

    ; OLED V1.3 新增
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306


; ============================================================
; 调试
; ============================================================

build_flags =
    -DCORE_DEBUG_LEVEL=0