[env:esp32-s3-devkitc-1]

platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino


; =========================
; 串口
; =========================
monitor_speed = 115200
upload_speed = 460800

upload_port = COM8
monitor_port = COM8


; =========================
; ESP32-S3-WROOM-2
; OPI Flash + OPI PSRAM
; =========================
board_build.arduino.memory_type = opi_opi
board_build.flash_mode = opi
board_build.psram_type = opi
board_build.f_flash = 80000000L


; =========================
; 传感器库
; =========================
lib_deps =
    adafruit/Adafruit MPU6050
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit BMP280 Library
    adafruit/Adafruit Unified Sensor


; =========================
; 编译参数
; =========================
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM