[env:esp32-s3-devkitc-1]

platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino


; ============================================================
; ESP32-S3-DevKitC-1 N32R16V
; 32MB Octal Flash + 16MB Octal PSRAM
; 已经跑通的配置，不修改
; ============================================================

board_build.arduino.memory_type = opi_opi
board_build.flash_mode = opi
board_build.psram_type = opi

board_upload.flash_size = 32MB

board_build.partitions = default_8MB.csv

board_build.extra_flags =
    -DBOARD_HAS_PSRAM


; ============================================================
; 串口
; ============================================================

monitor_speed = 115200
upload_speed = 460800

upload_port = COM8
monitor_port = COM8


; ============================================================
; 项目全部依赖
; ============================================================

lib_deps =

    ; MPU6050
    adafruit/Adafruit MPU6050

    ; BMP280 / BME280
    adafruit/Adafruit BMP280 Library
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit Unified Sensor

    ; GPS G60
    mikalhart/TinyGPSPlus @ 1.1.0

    ; 原 OLED 库
    ; 先保留，不删除
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306

    ; DS18B20 防水温度传感器
    paulstoffregen/OneWire
    milesburton/DallasTemperature

    ; 2.42寸 SSD1309 OLED 中文显示
    olikraus/U8g2


; ============================================================
; 调试
; ============================================================

build_flags =
    -DCORE_DEBUG_LEVEL=0